[project]
title = "Simple Project"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Simple Project"
logo = "images/74066467.png"
favicon = "images/74066467.ico"
primaryColor = "#df8e1d"

[data.used_car]
type = "csv"
path = "data/used_car_price_dataset.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 